# Generated by Django 3.0.7 on 2020-06-05 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bandas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=60)),
                ("ano_lancamento", models.IntegerField()),
                (
                    "banda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bandas.Banda"
                    ),
                ),
            ],
        ),
    ]
